name: Codino Kernel Python Nudge
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-python-nudge:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Dummy Python on Render
        run: |
          curl -X POST https://codino-kernel.onrender.com/execute \
          -H "Content-Type: application/json" \
          -d '{"code": "print(\"Ternel is Alive\")"}'
